config/routes.rb
Rails.application.routes.draw do
  get 'cards/show'
  resource :cards,only:[:show]
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'shops/index'
  get 'shops/show'
  resources :products
  resources :shops,only:[:index, :show]
resources :order_items
  root 'shops#index'
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal

before_save :set_total
before_save :set_unit_price
    def subtotal
        order_items.collect{|order_item| order.items? ? order_item.unit_price*order_item.quantity : 0}.sum

    end


    private

    def set_sub_total
        self[:sub_total]=subtotal


    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :product



    def unit_price
        if persisted?
            self[:unit_price]
        else 
            product.price
        end


    end


    def total
        unit_price*quantity


    end

    private

    def set_unit_price
        self[:unit_price]=unit_price

    end

    def set_total 
        set[:total]=total*quantity

    end

    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "id", "order_id", "product_id", "quantity", "total", "unit_price", "updated_at"]
      end
    
    


end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items

    def self.ransackable_associations(auth_object = nil)
        ["order_items"]
      end
      def self.ransackable_attributes(auth_object = nil)
        ["created_at", "id", "price", "title", "updated_at"]
      end
    
end

app/models/user.rb
class User < ApplicationRecord

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @order_items=current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

    def create
        @order=current_order
        @order_item = @order.order_items.new(order_params)
        #@order.before_save
        session[:order_id]=@order. id
    end



    def order_params
        params.require(:order_item).permit(:product_id, :quantity)
        

    end


   
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_admin_user!

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!
  def index
    @products=Product.all
    @order_item=current_order.order_items.new
  end

  def show
    @product=Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


    def current_order
        if session[:order_id].present?
          begin
            Order.find(session[:order_id])
          rescue ActiveRecord::RecordNotFound
            # Handle the case where the order with session[:order_id] doesn't exist
            # For example, reset the session[:order_id] to nil or create a new order
            session[:order_id] = nil
            Order.new
          end
        else
          Order.new
        end
      end
      

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/cards/show.html.erb
<% @order_items.each do |item| %>
    <h3><%= item.product.title %></h3>
    <h5><%= item.product.price %></h5>
    <%= form_for item do |f| %>
        <%= f.hidden_field :product_id, value: item.product.id %>
        <%= f.number_field :quantity, value: item.quantity.to_i %>
        <%= f.submit "Update Cart" %>
    <% end %>
<% end %>
# <h2>subtotal: <%#=item.total %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineShop23</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shop</h1>
</br>
<%=link_to 'clickhere if your admin',new_admin_user_session_path%>
</br>
</br>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
<tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', shop_path(product) %></td>
    <td>
        <%=form_for @order_item do |f| %>
           <%=f.hidden_field :product_id, :value => product.id%>
            <%=f.number_field :quantity, :value => 1, :min => 1%>
            <%=f.submit "Add to Cart"%>
        <%end%>
    </td>
</tr>
<%end%>


  </tbody>
</table>
<%=link_to "#{current_order.order_items.size} items with a value #{}$",cards_path%>

<br>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Priceeeeee:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Back', root_path %>